CREATE DATABASE LIBRARYDB ;
GO 
USE LIBRARYDB ;
GO 
--3MALNA TABLES
CREATE TABLE AUTHORS(
AUTHOR_ID INT PRIMARY KEY,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
DATEOFBIRTH DATE
);
CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
TITLE VARCHAR(100),
AUTHOR_ID INT,
GENRE VARCHAR(50),
PUBLISHEDYEAR INT,
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);
CREATE TABLE MEMBERS(
MEMBER_ID INT PRIMARY KEY,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR (50),
EMAIL VARCHAR (100),
PHONE_NUMBER VARCHAR (20),
);
CREATE TABLE BORROWED_BOOKS(
BORROW_ID INT PRIMARY KEY,
MEMBER_ID INT,
BOOK_ID INT,
BORROW_DATE DATE,
RETURN_DATE DATE,
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);
--BADELNA L ASSEMI MT3 TABLES WEL COLUMNS W ZEDNA COLUMN
ALTER TABLE BOOKS
ADD AVAILABILITYSTATUS VARCHAR(20);
EXEC sp_rename 'BOOKS', 'KTOB';
EXEC sp_rename 'MEMBERS.EMAIL','BARID';
ALTER TABLE MEMBERS
ALTER COLUMN BARID VARCHAR(80);
USE LIBRARYDB
ALTER TABLE KTOB
DROP COLUMN GENRE;
DROP TABLE BORROWED_BOOKS;
USE master
ALTER DATABASE LIBRARYDB
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
ALTER DATABASE LIBRARYDB
MODIFY NAME = FAHD;
DROP DATABASE FAHD;