USE master
CREATE DATABASE FAHD;
GO
CREATE TABLE EMPLOYEES(
EmployeeID INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Age INT CHECK (Age>0),
Salary DECIMAL(10,2)
);
USE FAHD
ALTER TABLE EMPLOYEES
ADD Department VARCHAR(50);

ALTER TABLE EMPLOYEES
ALTER COLUMN Salary INT;
ALTER TABLE EMPLOYEES
DROP COLUMN Department;
ALTER TABLE EMPLOYEES
ADD CONSTRAINT Name UNIQUE (Name);


CREATE TABLE DEPARTMENTS(
DepartmentID INT PRIMARY KEY,
DepartmentName varchar(50),
EmployeeID INT,
FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEES(EmployeeID)
);
ALTER TABLE EMPLOYEES
ADD DepartmentID INT;

DROP TABLE DEPARTMENTS;
TRUNCATE TABLE EMPLOYEES;

EXEC sp_rename 'EMPLOYEES','CREW';
EXEC sp_rename 'CREW','STAFF';

µ
ALTER TABLE STAFF
DROP DepartmentID;


