CREATE DATABASE PetStoreDB;
USE PetStoreDB;
CREATE TABLE OWNERS(
OwnerID INT PRIMARY KEY,
FirstName VARCHAR(50),
LastName VARCHAR (50),
ContactPhone VARCHAR(50),
);
CREATE TABLE PETS(
PetID INT PRIMARY KEY,
PetName VARCHAR (50),
OwnerID INT,
Species VARCHAR(50),
BirthDate DATE,
FOREIGN KEY (OwnerID) REFERENCES OWNERS(OwnerID)
);
CREATE TABLE STAFF(
StaffID INT PRIMARY KEY,
FirstName VARCHAR(50),
LastName VARCHAR (50),
JobTitle VARCHAR (50),
HiredDate DATE
);
CREATE TABLE PETSALES(
SaleID INT PRIMARY KEY,
PetID INT,
StaffID INT,
SaleDATE DATE,
SalePrice DECIMAL (10,2),
 FOREIGN KEY (PetID) REFERENCES PETS (PetID),
 FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);
ALTER TABLE PETS
ADD AdoptionStatus VARCHAR(20);
EXEC sp_rename 'PETS','STORESPETS';
INSERT INTO OWNERS(OwnerID,FirstName,LastName)
VALUES (1,'ANNA','SMITH'),
(2,'BEN','JONES');
SELECT * FROM OWNERS;
INSERT INTO OWNERS(OwnerID,FirstName,LastName,ContactPhone)
VALUES (4,'Ghazi','Lassoued');
SELECT * FROM OWNERS;
INSERT INTO STORESPETS(PetID,PetName,OwnerID,Species,BirthDate,AdoptionStatus)
VALUES (101,'FLUFFY',1,'CAT','2022-03-21','AVAILABLE'),
(102,'REX',2,'DOG','2021-05-22','AVAILABLE');
SELECT * FROM STORESPETS;
SELECT PetName FROM STORESPETS;
SELECT PetName,PetID FROM STORESPETS;
INSERT INTO STORESPETS(PetID,PetName,OwnerID,Species,BirthDate,AdoptionStatus)
VALUES (103,'FAHD',3,'LEOPARD','1994-09-01','ADOPTED');
SELECT * FROM STORESPETS;
SELECT * FROM STORESPETS
WHERE AdoptionStatus='AVAILABLE';
ALTER TABLE OWNERS
DROP COLUMN ContactPhone;
UPDATE STORESPETS
SET PetName='FAHDOUN'
WHERE PetName='FAHD';
SELECT * FROM STORESPETS;
DELETE FROM STORESPETS
WHERE PetName='FAHDOUN';
SELECT * FROM STORESPETS;
TRUNCATE TABLE OWNERS;
CREATE TABLE FOOD(
FoodID INT PRIMARY KEY,
typee VARCHAR(20)
);
INSERT INTO FOOD(FoodID,typee)
VALUES (24,'LACTOSE'),
(25,'GLUTEN');
SELECT * FROM FOOD;
TRUNCATE TABLE FOOD;
DROP TABLE FOOD;
SELECT * FROM FOOD;
ALTER DATABASE PetStoreDB
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
ALTER DATABASE PetStoreDB
MODIFY NAME=Caniche;
