SELECT 
    E.EMPLOYEE_NUMBER,
    E.FIRST_NAME,
    E.LAST_NAME,
    TIMESTAMPDIFF(YEAR, E.BIRTH_DATE, CURDATE()) AS AGE,
    TIMESTAMPDIFF(YEAR, E.HIRE_DATE, CURDATE()) AS SENIORITY
FROM 
    EMPLOYEES E
WHERE 
    E.COMMISSION IS NOT NULL
    AND E.SALARY + E.COMMISSION >= 8000
    AND E.POSITION = 'Male'
ORDER BY 
    SENIORITY DESC;

SELECT 
    P.PRODUCT_REF,
    P.PRODUCT_NAME,
    P.SUPPLIER_NUMBER,
    P.UNITS_ON_ORDER,
    P.UNIT_PRICE
FROM 
    PRODUCTS P
WHERE 
    P.QUANTITY = 'bottle(s)'
    AND UPPER(SUBSTRING(P.PRODUCT_NAME, 3, 1)) = 'T'
    AND P.SUPPLIER_NUMBER IN (1, 2, 3)
    AND P.UNIT_PRICE BETWEEN 70 AND 200
    AND P.UNITS_ON_ORDER IS NOT NULL;

SELECT 
    C.*
FROM 
    CUSTOMERS C
WHERE 
    C.COUNTRY = (SELECT S.COUNTRY FROM SUPPLIERS S WHERE S.SUPPLIER_NUMBER = 1)
    AND C.CITY = (SELECT S.CITY FROM SUPPLIERS S WHERE S.SUPPLIER_NUMBER = 1)
    AND RIGHT(C.POSTAL_CODE, 3) = (SELECT RIGHT(S.POSTAL_CODE, 3) FROM SUPPLIERS S WHERE S.SUPPLIER_NUMBER = 1);

SELECT 
    O.ORDER_NUMBER,
    CASE
        WHEN SUM(OD.UNIT_PRICE * OD.QUANTITY) BETWEEN 0 AND 2000 THEN '0%'
        WHEN SUM(OD.UNIT_PRICE * OD.QUANTITY) BETWEEN 2001 AND 10000 THEN '5%'
        WHEN SUM(OD.UNIT_PRICE * OD.QUANTITY) BETWEEN 10001 AND 40000 THEN '10%'
        WHEN SUM(OD.UNIT_PRICE * OD.QUANTITY) BETWEEN 40001 AND 80000 THEN '15%'
        ELSE '20%'
    END AS NEW_DISCOUNT_RATE,
    CASE
        WHEN O.ORDER_NUMBER BETWEEN 10000 AND 10999 THEN 'Apply old discount rate'
        ELSE 'Apply new discount rate'
    END AS DISCOUNT_RATE_APPLICATION_NOTE
FROM 
    ORDERS O
JOIN 
    ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
WHERE 
    O.ORDER_NUMBER BETWEEN 10998 AND 11003
GROUP BY 
    O.ORDER_NUMBER;
SELECT 
    S.SUPPLIER_NUMBER,
    S.COMPANY,
    S.ADDRESS,
    S.PHONE
FROM 
    SUPPLIERS S
JOIN 
    PRODUCTS P ON S.SUPPLIER_NUMBER = P.SUPPLIER_NUMBER
WHERE 
    P.PRODUCT_NAME LIKE '%beverage%';

SELECT 
    C.CUSTOMER_CODE
FROM 
    CUSTOMERS C
LEFT JOIN 
    ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
LEFT JOIN 
    ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
LEFT JOIN 
    PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_REF
WHERE 
    C.CITY = 'Berlin'
GROUP BY 
    C.CUSTOMER_CODE
HAVING 
    SUM(CASE WHEN P.PRODUCT_NAME LIKE '%dessert%' THEN 1 ELSE 0 END) <= 1;

SELECT 
    C.CUSTOMER_CODE,
    C.COMPANY,
    C.PHONE,
    COALESCE(SUM(OD.UNIT_PRICE * OD.QUANTITY), 0) AS TOTAL_AMOUNT,
    C.COUNTRY
FROM 
    CUSTOMERS C
LEFT JOIN 
    ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
LEFT JOIN 
    ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
WHERE 
    C.COUNTRY = 'France'
    AND O.ORDER_DATE BETWEEN '1998-04-01' AND '1998-04-30'
    AND DAYOFWEEK(O.ORDER_DATE) = 2 -- Monday
GROUP BY 
    C.CUSTOMER_CODE;


SELECT 
    C.CUSTOMER_CODE,
    C.COMPANY,
    C.PHONE
FROM 
    CUSTOMERS C
JOIN 
    ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN 
    ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
GROUP BY 
    C.CUSTOMER_CODE
HAVING 
    COUNT(DISTINCT OD.PRODUCT_REF) = (SELECT COUNT(*) FROM PRODUCTS);




SELECT 
    C.CUSTOMER_CODE,
    COUNT(O.ORDER_NUMBER) AS NUMBER_OF_ORDERS
FROM 
    CUSTOMERS C
LEFT JOIN 
    ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
WHERE 
    C.COUNTRY = 'France'
GROUP BY 
    C.CUSTOMER_CODE;




SELECT 
    (SELECT COUNT(*) FROM ORDERS WHERE ORDER_DATE BETWEEN '1996-01-01' AND '1996-12-31') AS ORDERS_IN_1996,
    (SELECT COUNT(*) FROM ORDERS WHERE ORDER_DATE BETWEEN '1997-01-01' AND '1997-12-31') AS ORDERS_IN_1997,
    (SELECT COUNT(*) FROM ORDERS WHERE ORDER_DATE BETWEEN '1997-01-01' AND '1997-12-31') - 
    (SELECT COUNT(*) FROM ORDERS WHERE ORDER_DATE BETWEEN '1996-01-01' AND '1996-12-31') AS DIFFERENCE;
