CREATE DATABASE cars;
USE cars;
CREATE TABLE Cars(
Registration_ID char(12) NOT NULL,
Model_ID VARCHAR(40) NOT NULL,
DateOfCirculation DATE NOT NULL,
Milage INT NOT NULL,
Requested_Price INT NOT NULL
);
CREATE TABLE Models(
Model_ID VARCHAR(40) NOT NULL,
Model VARCHAR(40) NOT NULL,
Brand VARCHAR(40) NOT NULL,
Horse_Power VARCHAR(5) NOT NULL
);
CREATE TABLE Person(
Person_ID INT NOT NULL,
Last_Name VARCHAR(12) NOT NULL,
First_Name VARCHAR(12) NOT NULL,
Email VARCHAR(100) NOT NULL,
Phone_Number INT
);
CREATE TABLE Acquisitions(
Registration_ID CHAR(12) NOT NULL,
Person_ID INT NOT NULL,
Start_Dates DATE NOT NULL,
End_Date DATE NOT NULL,
FOREIGN KEY (Person_ID) REFERENCES Person(Person_ID)
);
CREATE TABLE ContractSale(
Contact_ID CHAR (4) PRIMARY KEY NOT NULL,
Person_ID INT NOT NULL,
Registration_ID CHAR(12) NOT NULL,
Date_Sale DATE,
Price_Sale INT NOT NULL,
FOREIGN KEY (Person_ID) REFERENCES Person(Person_ID),
FOREIGN KEY (Registration_ID) REFERENCES Acquisitions(Registration_ID)
);
ALTER TABLE Cars
ADD CONSTRAINT Model_ID
FOREIGN KEY (Model_ID) REFERENCES Models(Model_ID)
ON DELETE CASCADE;
INSERT INTO Cars VALUES ('1245TUNIS99','RC','14/03/2001',155000,10200);
INSERT INTO Cars VALUES ('264TUNIS142','FF','11/02/2010',75000,19500);
INSERT INTO Cars VALUES ('569TUNIS122','PCC','02/10/2005',85250,15200);
INSERT INTO Cars VALUES ('1713TUNIS154','FPE','10/10/2012',106000,21000);

ALTER TABLE Cars
DROP Model_ID;

