CREATE DATABASE COFFEESHOP;
USE COFFEESHOP;
CREATE TABLE CUSTOMERS(
CustomerID INT PRIMARY KEY,
FirstName VARCHAR (50),
LastName VARCHAR (50),
LoyalityPoints INT
);
CREATE TABLE MenuItems(
ItemID INT PRIMARY KEY,
ItemName VARCHAR (50),
Price DECIMAL (10,2),
ItemType VARCHAR (20)
);
CREATE TABLE ORDERS(
OrderID INT PRIMARY KEY,
CustomerID INT,
OrderDate DATE,
TotalAmount DECIMAL (6,2),
FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);
CREATE TABLE ORDERDETAILS(
DetailID INT PRIMARY KEY,
OrderID INT,
ItemID INT,
Quantity INT,
FOREIGN KEY (OrderID) REFERENCES ORDERS (OrderID),
FOREIGN KEY (ItemID) REFERENCES MENUITEMS (ItemID)
);
INSERT INTO CUSTOMERS(CustomerID,FirstName,LastName,LoyalityPoints)
VALUES (1,'FAHD','BEJAOUI',1000),
(2,'GHAZI','LASSOUED',2000),
(3,'SOUAD','CHAIBI',3000);
SELECT * FROM CUSTOMERS;
UPDATE CUSTOMERS
SET LoyalityPoints=LoyalityPoints+10;

